apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-reviews.name" . }}
  labels:
    {{- include "product-reviews.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    quarkus.datasource.username={{ .Values.reviewsDb.user }}
    quarkus.datasource.password={{ .Values.reviewsDb.password }}
    quarkus.datasource.jdbc.url=jdbc:postgresql://{{ .Values.reviewsDb.service }}:5432/{{ .Values.reviewsDb.database }}
    quarkus.datasource.db-kind=postgresql
    quarkus.rest-client.reviews-sink.url={{ .Values.kafkaSink.reviews }}
