apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-reviews.name" . }}
  labels:
    {{- include "product-reviews.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "product-reviews.selectorLabels" . | nindent 4 }}
