---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "knative-kafkasource.name" . }}-secret
  labels:
    {{- include "knative-kafkasource.labels" . | nindent 4 }}
  annotations:
    {{- include "knative-kafkasource.secret.argocd-syncwave" . | nindent 4 }}
stringData:
  user: {{ .Values.kafka.clientId }}
  password: {{ .Values.kafka.clientSecret }}
  sasl.mechanism: {{ .Values.kafka.saslMechanism }}
type: Opaque
