apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: {{ include "knative-kafka.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "knative-kafka.argocd-syncwave" $ | nindent 4 }}
spec:
  channel:
    enabled: false
  source:
    enabled: true 
  broker:
    enabled: false
  sink:
    enabled: true
