kind: Secret
apiVersion: v1
metadata:
  name: {{ include "knative-kafkasink.name" . }}-secret
  labels:
    {{- include "knative-kafkasink.labels" . | nindent 4 }}
  annotations:
    {{- include "knative-kafkasink.secret.argocd-syncwave" . | nindent 4 }}
stringData:
  user: {{ .Values.kafka.clientId }}
  password: {{ .Values.kafka.clientSecret }}
  sasl.mechanism: {{ .Values.kafka.saslMechanism }}
  protocol: {{ .Values.kafka.securityProtocol }}
type: Opaque
