image:
  repository: quay.io/globex-sentiment-analysis/abusive-language-analysis-model-cloudevents
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations:
  autoscaling.knative.dev/min-scale: '1'

resources:
  limits:
    memory: 6000Mi
  requests:
    memory: 4000Mi

cloudEvents:
  source: reviews-sentiment
  type: reviews-sentiment-event

kafkaSink:
  sentiment: ""
