{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "globex-web-reviews.serviceAccountName" . }}
  labels:
    {{- include "globex-web-reviews.labels" . | nindent 4 }}
{{- end }}
